export const citybee = {
  cities: ["Tallinn", "Tartu"],
  cars: [
    {
      name: "Toyota Yaris",
      price: {
        km: 0.22,
        minute: 0.15,
        hour: 6.39,
        day: 28.39,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 17,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 25,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 33,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 52,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 70,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 65,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 91,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 118,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 105,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 126,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 161,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Peugeot 208",
      price: {
        km: 0.22,
        minute: 0.15,
        hour: 6.39,
        day: 28.39,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 17,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 25,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 33,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 52,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 70,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 65,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 91,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 118,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 105,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 126,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 161,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Citroen C3",
      price: {
        km: 0.22,
        minute: 0.15,
        hour: 6.39,
        day: 28.39,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 17,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 25,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 33,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 52,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 70,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 65,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 91,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 118,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 105,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 126,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 161,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Ford Fiesta",
      price: {
        km: 0.22,
        minute: 0.15,
        hour: 6.39,
        day: 28.39,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 17,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 25,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 33,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 52,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 70,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 65,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 91,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 118,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 105,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 126,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 161,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Toyota Corolla",
      price: {
        km: 0.24,
        minute: 0.17,
        hour: 7.19,
        day: 34.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 10,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 19,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 28,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 39,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 58,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 78,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 73,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 102,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 131,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 117,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 141,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 180,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 248,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 316,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 447,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 535,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 788,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 972,
        },
      ],
    },
    {
      name: "Volkswagen Golf 8",
      price: {
        km: 0.24,
        minute: 0.18,
        hour: 7.59,
        day: 35.39,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 10,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 19,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 28,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 39,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 59,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 79,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 74,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 104,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 133,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 118,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 143,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 182,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 251,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 320,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 454,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 542,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 800,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 986,
        },
      ],
    },
    {
      name: "Ford Focus",
      price: {
        km: 0.24,
        minute: 0.21,
        hour: 8.79,
        day: 39.49,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.5,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 32,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 43,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 64,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 84,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 81,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 113,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 145,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 129,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 156,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 199,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 275,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 350,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 495,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 592,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 874,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1077,
        },
      ],
    },
    {
      name: "BMW 118i",
      price: {
        km: 0.26,
        minute: 0.23,
        hour: 9.29,
        day: 44.49,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 12,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 23,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 34,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 48,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 71,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 93,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 90,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 126,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 144,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 174,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 307,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 391,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 553,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 661,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 975,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1202,
        },
      ],
    },
    {
      name: "Volkswagen T-Cross",
      price: {
        km: 0.24,
        minute: 0.18,
        hour: 7.59,
        day: 35.39,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 10,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 19,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 28,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 39,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 59,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 79,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 74,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 104,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 133,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 118,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 143,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 182,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 251,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 320,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 454,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 542,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 800,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 986,
        },
      ],
    },
    {
      name: "Nissan Juke",
      price: {
        km: 0.24,
        minute: 0.18,
        hour: 7.59,
        day: 35.39,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 10,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 19,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 28,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 39,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 59,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 79,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 74,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 104,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 133,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 118,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 143,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 182,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 251,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 320,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 454,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 542,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 800,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 986,
        },
      ],
    },
    {
      name: "Toyota C-HR",
      price: {
        km: 0.24,
        minute: 0.19,
        hour: 7.99,
        day: 35.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 10.5,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 20,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 29,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 40,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 60,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 80,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 75,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 105,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 135,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 120,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 145,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 185,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 255,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 325,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 460,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 550,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 811,
        },
        {
          days: 28,
          hours: 0,
          distance: 1000,
          price: 1039,
        },
      ],
    },
    {
      name: "Toyota Yaris Cross",
      price: {
        km: 0.24,
        minute: 0.2,
        hour: 8.39,
        day: 37.69,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 21,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 31,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 42,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 62,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 83,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 78,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 109,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 140,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 125,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 192,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 265,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 338,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 478,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 571,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 842,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1039,
        },
      ],
    },
    {
      name: "Volkswagen Taigo",
      price: {
        km: 0.24,
        minute: 0.2,
        hour: 8.39,
        day: 37.69,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 21,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 31,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 42,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 62,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 83,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 78,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 109,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 140,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 125,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 192,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 265,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 338,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 478,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 571,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 842,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1039,
        },
      ],
    },
    {
      name: "Peugeot 2008",
      price: {
        km: 0.24,
        minute: 0.21,
        hour: 8.79,
        day: 39.49,
      },
      packages: [],
    },
    {
      name: "Volkswagen T-Roc",
      price: {
        km: 0.25,
        minute: 0.22,
        hour: 9.19,
        day: 41.29,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 12,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 23,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 34,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 45,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 67,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 88,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 84,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 118,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 134,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 207,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 286,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 364,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 515,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 616,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 908,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1120,
        },
      ],
    },
    {
      name: "Volkswagen T-Roc R-Line",
      price: {
        km: 0.26,
        minute: 0.23,
        hour: 9.75,
        day: 45.99,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 12,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 23,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 34,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 48,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 72,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 94,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 90,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 126,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 144,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 174,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 305,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 389,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 551,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 659,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 971,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1198,
        },
      ],
    },
    {
      name: "Jeep Compass",
      price: {
        km: 0.26,
        minute: 0.23,
        hour: 9.75,
        day: 45.99,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 12,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 23,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 34,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 48,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 72,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 94,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 90,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 126,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 144,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 174,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 305,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 389,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 551,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 659,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 971,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1198,
        },
      ],
    },
    {
      name: "Ford Kuga",
      price: {
        km: 0.26,
        minute: 0.23,
        hour: 9.75,
        day: 45.99,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 12,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 23,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 34,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 48,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 72,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 94,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 90,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 126,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 144,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 174,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 305,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 389,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 551,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 659,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 971,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1198,
        },
      ],
    },
    {
      name: "Toyota RAV4",
      price: {
        km: 0.27,
        minute: 0.24,
        hour: 9.84,
        day: 48.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 12.5,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 24,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 35,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 50,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 76,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 99,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 94,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 132,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 170,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 183,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 233,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 321,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 409,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 579,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 693,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 1021,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1259,
        },
      ],
    },
    {
      name: "BMW X1",
      price: {
        km: 0.29,
        minute: 0.27,
        hour: 10.99,
        day: 52.99,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 14,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 27,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 40,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 55,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 82,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 107,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 104,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 145,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 186,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 166,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 200,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 256,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 352,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 449,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 635,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 760,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 1120,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1381,
        },
      ],
    },
    {
      name: "Skoda Kamiq",
      price: {
        km: 0.25,
        minute: 0.22,
        hour: 9.19,
        day: 41.29,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 12,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 23,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 34,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 45,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 67,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 88,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 84,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 118,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 134,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 207,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 286,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 364,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 515,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 616,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 908,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1120,
        },
      ],
    },
    {
      name: "Volkswagen Crafter",
      price: {
        km: 0.27,
        minute: 0.27,
        hour: 8.9,
        day: 39.9,
      },
      packages: [
        {
          days: 7,
          hours: 0,
          distance: 100,
          price: 260,
        },
        {
          days: 14,
          hours: 0,
          distance: 200,
          price: 520,
        },
        {
          days: 28,
          hours: 0,
          distance: 750,
          price: 800,
        },
      ],
    },
    {
      name: "Renault Master",
      price: {
        km: 0.27,
        minute: 0.27,
        hour: 8.9,
        day: 39.9,
      },
      packages: [
        {
          days: 7,
          hours: 0,
          distance: 100,
          price: 260,
        },
        {
          days: 14,
          hours: 0,
          distance: 200,
          price: 520,
        },
        {
          days: 28,
          hours: 0,
          distance: 750,
          price: 800,
        },
      ],
    },
  ],
};
