export const avis = {
  cities: ["Tallinn"],
  cars: [
    {
      name: "Toyota Corolla",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearbox: "AUTOMATIC",
      imageUrl: "providers/avis/cars/Toyota-Corolla.png",
      price: {
        km: 0.15,
        minute: 0.11,
        hour: 4.9,
        day: 23.9,
      },
    },
    {
      name: "Peugeot 308",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearbox: "AUTOMATIC",
      imageUrl: "providers/avis/cars/Peugeot-308.png",
      price: {
        km: 0.15,
        minute: 0.11,
        hour: 4.9,
        day: 23.9,
      },
    },
    {
      name: "Škoda Scala",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearbox: "AUTOMATIC",
      imageUrl: "providers/avis/cars/Scoda-Scala.png",
      price: {
        km: 0.15,
        minute: 0.11,
        hour: 4.9,
        day: 23.9,
      },
    },
    {
      name: "Toyota Yaris Cross",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearbox: "AUTOMATIC",
      imageUrl: "providers/avis/cars/Toyota-Yaris-Cross.png",
      price: {
        km: 0.15,
        minute: 0.11,
        hour: 4.9,
        day: 23.9,
      },
    },
    {
      name: "BMW 118i",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearbox: "AUTOMATIC",
      imageUrl: "providers/avis/cars/BMW-118i.png",
      price: {
        km: 0.25,
        minute: 0.2,
        hour: 6.9,
        day: 31.9,
      },
    },
    {
      name: "Mini Cooper",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearbox: "AUTOMATIC",
      imageUrl: "providers/avis/cars/Mini-Cooper.png",
      price: {
        km: 0.25,
        minute: 0.2,
        hour: 6.9,
        day: 31.9,
      },
    },
  ],
};
