export const beast = {
  cities: ["Tallinn", "Tartu", "Pärnu"],
  cars: [
    {
      name: "Tesla Model 3 Standard Range",
      bodyType: "SEDAN",
      motorType: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.2,
        first30mins: 14.99,
        minute: 0.22,
        day: 119.99,
        "3days": 289.99,
        week: 549.99,
      },
    },
    {
      name: "Tesla Model 3 Long Range",
      bodyType: "SEDAN",
      motorType: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.2,
        first30mins: 19.99,
        minute: 0.25,
        day: 139.99,
        "3days": 339.99,
        week: 649.99,
      },
    },
    {
      name: "Tesla Model 3 Performance",
      bodyType: "SEDAN",
      motorType: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.2,
        first30mins: 24.99,
        minute: 0.29,
        day: 159.99,
        "3days": 379.99,
        week: 749.99,
      },
    },
    {
      name: "Tesla Model Y Long Range",
      bodyType: "TOURING",
      motorType: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.25,
        first30mins: 24.99,
        minute: 0.35,
        day: 189.99,
        "3days": 459.99,
        week: 899.99,
      },
    },
    {
      name: "Tesla Model X Ludicrous Perf",
      bodyType: "TOURING",
      motorType: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.3,
        first30mins: 39.99,
        minute: 0.49,
        day: 269.99,
        "3days": 649.99,
        week: 1299.99,
      },
    },
  ],
};
