export const bolt = {
  cities: ["Tallinn"],
  cars: [
    {
      name: "Toyota Corolla",
      bodyType: "HATCHBACK",
      motor: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    //   {
    //     name: "Škoda Octavia",
    //     price: {
    //       km: 0.23,
    //       minute: 0.12,
    //       hour: 4.99,
    //       day: 27.9,
    //     },
    //   },
    {
      name: "Audi A1",
      bodyType: "HATCHBACK",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.22,
        minute: 0.16,
        hour: 7.99,
        day: 30.9,
      },
    },
    {
      name: "Audi A3",
      bodyType: "HATCHBACK",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.16,
        hour: 7.99,
        day: 30.9,
      },
    },
    {
      name: "Hyundai i20",
      bodyType: "HATCHBACK",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.23,
        minute: 0.12,
        hour: 4.99,
        day: 27.9,
      },
    },
    {
      name: "Toyota Yaris",
      bodyType: "HATCHBACK",
      motor: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.2,
        minute: 0.12,
        hour: 4.49,
        day: 19.9,
      },
    },
    {
      name: "Škoda Scala",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    {
      name: "Škoda Fabia",
      bodyType: "HATCHBACK",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.23,
        minute: 0.12,
        hour: 4.99,
        day: 27.9,
      },
    },
    {
      name: "VW ID.3",
      bodyType: "HATCHBACK",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 7.39,
        day: 33.9,
      },
    },
    {
      name: "Toyota Yaris Cross",
      bodyType: "TOURING",
      motor: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    {
      name: "VW T-Cross",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.15,
        hour: 6.79,
        day: 30.9,
      },
    },
    {
      name: "Audi Q2",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.16,
        hour: 7.99,
        day: 30.9,
      },
    },
    {
      name: "VW T-Roc",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.15,
        hour: 6.79,
        day: 30.9,
      },
    },
    {
      name: "Škoda Kamiq",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    {
      name: "Toyota C-HR",
      bodyType: "TOURING",
      motor: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    {
      name: "Audi e-tron",
      bodyType: "TOURING",
      motor: "ELECTRIC",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.25,
        minute: 0.69,
        hour: 39.9,
        day: 149.9,
      },
    },
    {
      name: "Toyota RAV4",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.25,
        minute: 0.3,
        hour: 12.9,
        day: 43.9,
      },
    },
    {
      name: "BMW 4 Convertible",
      bodyType: "CABRIOLET",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.35,
        minute: 0.49,
        hour: 25,
        day: 119.9,
      },
    },
    {
      name: "VW T-Roc Cabrio",
      bodyType: "CABRIOLET",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.25,
        minute: 0.3,
        hour: 16.9,
        day: 54.9,
      },
    },
    {
      name: "VW Arteon",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.25,
        minute: 0.3,
        hour: 12.9,
        day: 43.9,
      },
    },
    {
      name: "Toyota Land Cruiser",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.34,
        minute: 0.49,
        hour: 19.9,
        day: 79.9,
      },
    },
    {
      name: "Mercedes Sprinter",
      bodyType: "VAN",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.27,
        minute: 0.15,
        hour: 6.9,
        day: 37.9,
      },
    },
    {
      name: "VW Crafter",
      bodyType: "VAN",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.27,
        minute: 0.13,
        hour: 6.9,
        day: 35.9,
      },
    },
    {
      name: "VW Crafter",
      bodyType: "VAN",
      motor: "ELECTRIC",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.27,
        minute: 0.13,
        hour: 6.9,
        day: 35.9,
      },
    },
    {
      name: "Audi Q8",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.35,
        minute: 0.84,
        hour: 49.9,
        day: 249,
      },
    },
  ],
};
