export const bolt = {
  cities: ["Tallinn", "Tartu"],
  cars: [
    {
      name: "Toyota Corolla",
      bodyType: "HATCHBACK",
      motorType: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-07-08/455bd1fc-9e91-4fd0-97a3-af7706cee2bb.png",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    //   {
    //     name: "Škoda Octavia",
    //     price: {
    //       km: 0.23,
    //       minute: 0.12,
    //       hour: 4.99,
    //       day: 27.9,
    //     },
    //   },
    {
      name: "Audi A1",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-02-14/1f86602a-bcb9-43fb-b810-0d62dc94d725.png",
      price: {
        km: 0.22,
        minute: 0.16,
        hour: 7.99,
        day: 30.9,
      },
    },
    {
      name: "Audi A3",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.24,
        minute: 0.16,
        hour: 7.99,
        day: 30.9,
      },
    },
    {
      name: "Hyundai i20",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2021/2021-08-04/f818348d-dfe7-457a-b7ec-2d13f3d152fd.png",
      price: {
        km: 0.23,
        minute: 0.12,
        hour: 4.99,
        day: 27.9,
      },
    },
    {
      name: "Toyota Yaris",
      bodyType: "HATCHBACK",
      motorType: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl: "https://images.bolt.eu/rentals/car_models/yaris_black.png",
      price: {
        km: 0.2,
        minute: 0.12,
        hour: 4.49,
        day: 19.9,
      },
    },
    {
      name: "Škoda Scala",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl: "https://images.bolt.eu/rentals/car_models/scala_grey.png",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    {
      name: "Škoda Fabia",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-05-25/839c7880-6862-4488-8bdd-6c22825c6bf9.png",
      price: {
        km: 0.23,
        minute: 0.12,
        hour: 4.99,
        day: 27.9,
      },
    },
    {
      name: "VW ID.3",
      bodyType: "HATCHBACK",
      motorType: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl: "https://images.bolt.eu/rentals/car_models/id3_blue.png",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 7.39,
        day: 33.9,
      },
    },
    {
      name: "Toyota Yaris Cross",
      bodyType: "TOURING",
      motorType: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-07-28/620bdf8c-6ef3-421c-a59a-be75029e58d0.png",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    {
      name: "VW T-Cross",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-05-25/252bb77f-1ac0-4b34-b11d-80a2f9b76644.png",
      price: {
        km: 0.24,
        minute: 0.15,
        hour: 6.79,
        day: 30.9,
      },
    },
    {
      name: "Audi Q2",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-04-20/4efda9a2-90f6-4d2f-8e05-3ed6de45fb61.png",
      price: {
        km: 0.24,
        minute: 0.16,
        hour: 7.99,
        day: 30.9,
      },
    },
    {
      name: "VW T-Roc",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl: "https://images.bolt.eu/rentals/car_models/troc_grey.png",
      price: {
        km: 0.24,
        minute: 0.15,
        hour: 6.79,
        day: 30.9,
      },
    },
    {
      name: "Škoda Kamiq",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl: "https://images.bolt.eu/rentals/car_models/kamiq_white.png",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    {
      name: "Toyota C-HR",
      bodyType: "TOURING",
      motorType: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-07-29/9464e2e0-0fb8-43fd-9518-41f397a61775.png",
      price: {
        km: 0.24,
        minute: 0.14,
        hour: 5.89,
        day: 27.9,
      },
    },
    {
      name: "Audi e-tron",
      bodyType: "TOURING",
      motorType: "ELECTRIC",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-04-20/f6375ab4-5302-4155-8006-e4596eea9c20.png",
      price: {
        km: 0.25,
        minute: 0.69,
        hour: 39.9,
        day: 149.9,
      },
    },
    {
      name: "Toyota RAV4",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-01-21/afca4b89-6439-4e58-8ee9-7700736e7026.png",
      price: {
        km: 0.25,
        minute: 0.3,
        hour: 12.9,
        day: 43.9,
      },
    },
    {
      name: "BMW 4 Convertible",
      bodyType: "CABRIOLET",
      motorType: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      price: {
        km: 0.35,
        minute: 0.49,
        hour: 25,
        day: 119.9,
      },
    },
    {
      name: "VW T-Roc Cabrio",
      bodyType: "CABRIOLET",
      motorType: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/rentals/car_models/vw_troc_cabrio_gray_v2.png",
      price: {
        km: 0.25,
        minute: 0.3,
        hour: 16.9,
        day: 54.9,
      },
    },
    {
      name: "VW Arteon",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-09-12/056e744f-53d8-4ad4-a863-8cf76730c0dd.png",
      price: {
        km: 0.25,
        minute: 0.3,
        hour: 12.9,
        day: 43.9,
      },
    },
    {
      name: "Toyota Land Cruiser",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-02-14/1f86602a-bcb9-43fb-b810-0d62dc94d725.png",
      price: {
        km: 0.34,
        minute: 0.49,
        hour: 19.9,
        day: 79.9,
      },
    },
    {
      name: "Mercedes Sprinter",
      bodyType: "VAN",
      motorType: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-06-02/57c2f81c-a9a5-49f0-a818-b18dba854633.png",
      price: {
        km: 0.27,
        minute: 0.15,
        hour: 6.9,
        day: 37.9,
      },
    },
    {
      name: "VW Crafter",
      bodyType: "VAN",
      motorType: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/rentals/car_models/vw_crafter_white.png",
      price: {
        km: 0.27,
        minute: 0.13,
        hour: 6.9,
        day: 35.9,
      },
    },
    {
      name: "VW Crafter",
      bodyType: "VAN",
      motorType: "ELECTRIC",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/rentals/car_models/vw_crafter_white.png",
      price: {
        km: 0.27,
        minute: 0.13,
        hour: 6.9,
        day: 35.9,
      },
    },
    // {
    //   name: "Audi Q8",
    //   bodyType: "TOURING",
    //   motorType: "PETROL",
    //   petFriendly: false,
    //   gearBox: "AUTOMATIC",
    //   price: {
    //     km: 0.35,
    //     minute: 0.84,
    //     hour: 49.9,
    //     day: 249,
    //   },
    // },
    {
      name: "Audi Q5",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
      imageUrl:
        "https://images.bolt.eu/store/2022/2022-09-01/b41c596d-eed8-4618-b9d5-bcd97e96919e.png",
      price: {
        min: 7.99,
        km: 0.35,
        minute: 0.69,
        hour: 39.9,
        day: 149.9,
      },
    },
  ],
};
