export const citybee = {
  cities: ["Tallinn", "Tartu"],
  cars: [
    {
      name: "Toyota Yaris",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.ee/wp-content/uploads/2021/08/CityBee_ToyotaYaris_EE-768x454.png",
      price: {
        km: 0.22,
        minute: 0.13,
        hour: 4.99,
        day: 27.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 7.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 13.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 19.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 31,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 49,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 64,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 60,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 108,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 96,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 116,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 148,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Škoda Fabia",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.lt/wp-content/uploads/2021/07/Skoda-Fabia-WhiteMoon-768x454.png",
      price: {
        km: 0.22,
        minute: 0.13,
        hour: 4.99,
        day: 27.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 7.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 13.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 19.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 31,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 49,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 64,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 60,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 108,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 96,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 116,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 148,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Peugeot 208",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.ee/wp-content/uploads/2021/08/CityBee_Peugeot208_EE-768x454.png",
      price: {
        km: 0.22,
        minute: 0.13,
        hour: 4.99,
        day: 27.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 7.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 13.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 19.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 31,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 49,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 64,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 60,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 108,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 96,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 116,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 148,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Citroen C3",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url: "https://citybee.ee/wp-content/uploads/2022/04/Citroen-C3.png",
      price: {
        km: 0.22,
        minute: 0.13,
        hour: 4.99,
        day: 27.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 7.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 13.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 19.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 31,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 49,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 64,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 60,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 108,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 96,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 116,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 148,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Renault Clio",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/bffb20e1-1174-42be-9310-8859b7889215.png",
      price: {
        km: 0.22,
        minute: 0.13,
        hour: 4.99,
        day: 27.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 7.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 13.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 19.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 31,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 49,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 64,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 60,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 108,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 96,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 116,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 148,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Ford Fiesta",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/c17b0635-cc06-4f6d-8c57-714d9be67f35.png",
      price: {
        km: 0.22,
        minute: 0.13,
        hour: 4.99,
        day: 27.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 7.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 13.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 19.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 31,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 49,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 64,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 60,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 85,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 108,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 96,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 116,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 148,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 283,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 401,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 479,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 706,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 871,
        },
      ],
    },
    {
      name: "Toyota Corolla",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.ee/wp-content/uploads/2021/08/CityBee_ToyotaCorolla_Hatch_EE-768x454.png",
      price: {
        km: 0.24,
        minute: 0.15,
        hour: 6.19,
        day: 29.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 8.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 16.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 24.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 35,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 55,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 72,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 94,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 67,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 94,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 120,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 106,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 129,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 164,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 248,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 316,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 447,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 535,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 788,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 972,
        },
      ],
    },
    {
      name: "Volkswagen Golf 8",
      TbodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.ee/wp-content/uploads/2021/08/CityBee_VW_Golf8_EE-768x454.png",
      price: {
        km: 0.24,
        minute: 0.16,
        hour: 6.99,
        day: 33.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 18.49,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 26.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 36,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 56,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 75,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 97,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 69,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 97,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 124,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 110,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 133,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 170,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 251,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 320,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 454,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 542,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 800,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 986,
        },
      ],
    },
    {
      name: "Ford Focus",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/e934c126-121e-4cad-904a-090cc90b8969.png",
      price: {
        km: 0.24,
        minute: 0.21,
        hour: 8.79,
        day: 39.49,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 21.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 31.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 43,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 64,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 84,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 105,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 81,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 113,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 145,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 129,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 156,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 199,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 275,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 350,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 495,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 592,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 874,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1077,
        },
      ],
    },
    {
      name: "BMW 118i",
      bodyType: "HATCHBACK",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url: "https://citybee.ee/wp-content/uploads/2022/04/BMW-118i.png",
      price: {
        km: 0.26,
        minute: 0.23,
        hour: 9.29,
        day: 44.49,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 33.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 48,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 71,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 93,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 120,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 90,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 126,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 144,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 174,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 307,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 391,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 553,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 661,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 975,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1202,
        },
      ],
    },
    {
      name: "Volkswagen T-Cross",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.ee/wp-content/uploads/2021/08/CityBee_VW_T-Cross_EE-768x454.png",
      price: {
        km: 0.24,
        minute: 0.16,
        hour: 6.99,
        day: 33.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 18.49,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 26.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 36,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 56,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 75,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 97,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 69,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 97,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 124,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 110,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 133,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 170,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 251,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 320,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 454,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 542,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 800,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 986,
        },
      ],
    },
    {
      name: "Nissan Juke",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/baea33ea-0305-4b67-a598-b5fc0950830e.png",
      price: {
        km: 0.24,
        minute: 0.16,
        hour: 6.99,
        day: 33.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 18.49,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 26.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 36,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 56,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 75,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 97,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 69,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 97,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 124,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 110,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 133,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 170,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 251,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 320,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 454,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 542,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 800,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 986,
        },
      ],
    },
    {
      name: "Volkswagen T-Roc",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.ee/wp-content/uploads/2021/08/VW_TRoc_icon_EE-768x454.png",
      price: {
        km: 0.24,
        minute: 0.16,
        hour: 6.99,
        day: 33.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 18.49,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 26.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 36,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 56,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 75,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 97,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 69,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 97,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 124,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 110,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 133,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 170,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 251,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 320,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 454,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 542,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 800,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 986,
        },
      ],
    },
    {
      name: "Volkswagen T-Roc R-Line",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/4fdef8e0-0036-4621-aff9-66e55634b161.png",
      price: {
        km: 0.26,
        minute: 0.18,
        hour: 7.49,
        day: 36.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 18.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 27.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 42,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 65,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 87,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 113,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 79,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 112,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 143,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 126,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 153,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 195,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 269,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 343,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 486,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 580,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 857,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1071,
        },
      ],
    },
    {
      name: "Toyota C-HR",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/d3245015-188e-42bd-b0aa-e98d58e0926f.png",
      price: {
        km: 0.24,
        minute: 0.19,
        hour: 7.99,
        day: 35.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 10.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 19.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 28.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 40,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 60,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 80,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 100,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 75,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 105,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 135,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 120,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 145,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 185,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 255,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 325,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 460,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 550,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 811,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1000,
        },
      ],
    },
    {
      name: "Toyota Yaris Cross",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.ee/wp-content/uploads/2022/04/83155c4c-f137-4ebc-881e-9d51728aa1a5.png",
      price: {
        km: 0.24,
        minute: 0.2,
        hour: 8.39,
        day: 37.69,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 10.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 20.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 30.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 42,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 62,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 83,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 105,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 78,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 109,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 140,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 125,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 192,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 265,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 338,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 478,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 571,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 842,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1039,
        },
      ],
    },
    {
      name: "Volkswagen Taigo",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/a7ef1ef2-2ace-454a-8151-2adff796644e.png",
      price: {
        km: 0.24,
        minute: 0.2,
        hour: 8.39,
        day: 37.69,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 10.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 20.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 30.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 42,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 62,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 83,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 105,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 78,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 109,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 140,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 125,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 192,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 265,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 338,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 478,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 571,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 842,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1039,
        },
      ],
    },
    // {
    // name: "Peugeot 2008",
    // bodyType: "TOURING",
    // motorType: "PETROL",
    // petFriendly: true,
    // gearBox: "AUTOMATIC",
    // price: {
    //   km: 0.24,
    //   minute: 0.21,
    //   hour: 8.79,
    //   day: 39.49,
    // },
    // packages: [],
    // },
    {
      name: "Jeep Compass",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/929e0d52-b2c6-4ac4-a6e7-a7443d7a12cd.png",
      price: {
        km: 0.26,
        minute: 0.23,
        hour: 9.49,
        day: 44.99,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 33.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 48,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 72,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 94,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 120,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 90,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 126,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 144,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 174,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 305,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 389,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 551,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 659,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 971,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1198,
        },
      ],
    },
    {
      name: "Ford Kuga",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/f374da70-1919-4b4d-ba6f-59308a9f6c04.png",
      price: {
        km: 0.26,
        minute: 0.23,
        hour: 9.49,
        day: 44.99,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 33.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 48,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 72,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 94,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 120,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 90,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 126,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 144,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 174,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 305,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 389,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 551,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 659,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 971,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1198,
        },
      ],
    },
    {
      name: "Toyota RAV4",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/a9426700-c1a5-4b42-a54a-9878b0639393.png",
      price: {
        km: 0.27,
        minute: 0.24,
        hour: 9.84,
        day: 48.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 12.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 23.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 34.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 50,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 76,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 99,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 125,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 94,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 132,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 170,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 183,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 233,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 321,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 409,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 579,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 693,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 1021,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1259,
        },
      ],
    },
    {
      name: "BMW X1",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://citybee.ee/wp-content/uploads/2022/04/a6777e26-f06c-415a-862e-6ff339324285.png",
      price: {
        km: 0.29,
        minute: 0.27,
        hour: 10.99,
        day: 52.99,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 13.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 26.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 39.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 55,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 82,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 107,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 135,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 104,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 145,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 186,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 166,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 200,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 256,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 352,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 449,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 635,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 760,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 1120,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1381,
        },
      ],
    },
    {
      name: "Skoda Kamiq",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/af626c4e-7247-4437-a6b5-6dc9e475a27b.png",
      price: {
        km: 0.25,
        minute: 0.16,
        hour: 6.99,
        day: 33.89,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 9.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 17.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 26.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 40,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 61,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 81,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 105,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 74,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 104,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 133,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 117,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 142,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 181,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 250,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 318,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 452,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 539,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 796,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 995,
        },
      ],
    },
    {
      name: "Nissan Qashqai",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/78ada031-ad89-4441-88d5-3813ffacef89.png",
      price: {
        km: 0.26,
        minute: 0.23,
        hour: 9.49,
        day: 44.99,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 33.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 48,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 72,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 94,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 120,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 90,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 126,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 144,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 174,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 222,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 305,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 389,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 551,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 659,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 971,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1198,
        },
      ],
    },
    {
      name: "Renault Arkana",
      bodyType: "TOURING",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      image_url:
        "https://files-ee.citybee.tech/images/af98ce28-1940-4d8d-b5c3-74dd2cb95f2d.png",
      price: {
        km: 0.25,
        minute: 0.22,
        hour: 9.19,
        day: 41.29,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.99,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22.99,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 33.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 45,
        },
        {
          days: 1,
          hours: 0,
          distance: 150,
          price: 67,
        },
        {
          days: 1,
          hours: 0,
          distance: 250,
          price: 88,
        },
        {
          days: 1,
          hours: 0,
          distance: 350,
          price: 110,
        },
        {
          days: 2,
          hours: 0,
          distance: 100,
          price: 84,
        },
        {
          days: 2,
          hours: 0,
          distance: 250,
          price: 118,
        },
        {
          days: 2,
          hours: 0,
          distance: 400,
          price: 151,
        },
        {
          days: 3,
          hours: 0,
          distance: 175,
          price: 134,
        },
        {
          days: 3,
          hours: 0,
          distance: 300,
          price: 162,
        },
        {
          days: 3,
          hours: 0,
          distance: 500,
          price: 207,
        },
        {
          days: 7,
          hours: 0,
          distance: 600,
          price: 286,
        },
        {
          days: 7,
          hours: 0,
          distance: 900,
          price: 364,
        },
        {
          days: 14,
          hours: 0,
          distance: 600,
          price: 515,
        },
        {
          days: 14,
          hours: 0,
          distance: 1000,
          price: 616,
        },
        {
          days: 28,
          hours: 0,
          distance: 1800,
          price: 908,
        },
        {
          days: 28,
          hours: 0,
          distance: 2500,
          price: 1120,
        },
      ],
    },
    {
      name: "Volkswagen Crafter",
      bodyType: "VAN",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "MANUAL",
      image_url:
        "https://files-ee.citybee.tech/images/192b86c6-f153-45b2-bf98-151396fffae2.png",
      price: {
        km: 0.27,
        minute: 0.27,
        hour: 8.9,
        day: 39.9,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22.49,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 32.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 50,
        },

        {
          days: 2,
          hours: 0,
          distance: 50,
          price: 85,
        },
        {
          days: 3,
          hours: 0,
          distance: 50,
          price: 118,
        },
        {
          days: 7,
          hours: 0,
          distance: 100,
          price: 260,
        },
        {
          days: 14,
          hours: 0,
          distance: 200,
          price: 520,
        },
        {
          days: 28,
          hours: 0,
          distance: 750,
          price: 800,
        },
      ],
    },
    {
      name: "Renault Master",
      bodyType: "VAN",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "MANUAL",
      image_url:
        "https://files-ee.citybee.tech/images/be81a2a2-e1ef-4db6-8830-610ea70c7349.png",
      price: {
        km: 0.27,
        minute: 0.27,
        hour: 8.9,
        day: 39.9,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22.49,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 32.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 50,
        },

        {
          days: 2,
          hours: 0,
          distance: 50,
          price: 85,
        },
        {
          days: 3,
          hours: 0,
          distance: 50,
          price: 118,
        },
        {
          days: 7,
          hours: 0,
          distance: 100,
          price: 260,
        },
        {
          days: 14,
          hours: 0,
          distance: 200,
          price: 520,
        },
        {
          days: 28,
          hours: 0,
          distance: 750,
          price: 800,
        },
      ],
    },
    {
      name: "Ford Transit",
      bodyType: "VAN",
      motorType: "PETROL",
      petFriendly: true,
      gearBox: "MANUAL",
      image_url:
        "https://files-ee.citybee.tech/images/a94092de-4686-47b7-a406-fe05def6d61a.png",
      price: {
        km: 0.27,
        minute: 0.27,
        hour: 8.9,
        day: 39.9,
      },
      packages: [
        {
          days: 0,
          hours: 1,
          distance: 10,
          price: 11.49,
        },
        {
          days: 0,
          hours: 2,
          distance: 20,
          price: 22.49,
        },
        {
          days: 0,
          hours: 3,
          distance: 30,
          price: 32.99,
        },
        {
          days: 1,
          hours: 0,
          distance: 50,
          price: 50,
        },

        {
          days: 2,
          hours: 0,
          distance: 50,
          price: 85,
        },
        {
          days: 3,
          hours: 0,
          distance: 50,
          price: 118,
        },
        {
          days: 7,
          hours: 0,
          distance: 100,
          price: 260,
        },
        {
          days: 14,
          hours: 0,
          distance: 200,
          price: 520,
        },
        {
          days: 28,
          hours: 0,
          distance: 750,
          price: 800,
        },
      ],
    },
  ],
};
