export const elmo = {
  cities: ["Tallinn", "Tartu"],
  cars: [
    {
      name: "Rent1",
      bodyType: "HATCHBACK",
      motor: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      cars: [
        "Volkswagen e-Up '19",
        "Skoda Citigo",
        "Toyota Yaris",
        "Nissan Leaf",
      ],

      price: {
        km: 0.2,
        minute: 0.11,
        hour: 6.6,
        day: 30,
        week: 225,
        month: 700,
      },
    },
    {
      name: "Rent2",
      bodyType: "HATCHBACK",
      motor: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      cars: ["Volkswagen e-Up '20", "Renault Clio"],
      price: {
        km: 0.2,
        minute: 0.11,
        hour: 6.6,
        day: 35,
        week: 260,
        month: 799,
      },
    },
    {
      name: "Rent3",
      bodyType: "HATCHBACK",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      cars: ["Renault Zoe", "Peugeot e-208 GT"],
      price: {
        km: 0.2,
        minute: 0.13,
        hour: 7.8,
        day: 42,
        week: 275,
        month: 825,
      },
    },
    {
      name: "Rent4",
      bodyType: "TOURING",
      motor: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      cars: ["Renault Arkana", "Audi A5"],
      price: {
        km: 0.22,
        minute: 0.15,
        hour: 9,
        day: 49,
        week: 350,
        month: 890,
      },
    },
    {
      name: "Rent5",
      bodyType: "SEDAN",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      cars: ["Tesla Model 3 SR+"],
      price: {
        km: 0.22,
        minute: 0.25,
        hour: 15,
        day: 99,
        week: 525,
        month: 1599,
      },
      min_price: 30,
    },
  ],
};
