export const offersTestData = [
  {
    id: 1,
    car: {
      name: "Toyota Corolla",
      bodyType: "HATCHBACK",
      motor: "HYBRID",
      petFriendly: true,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "bolt",
  },
  {
    id: 2,
    car: {
      name: "Toyota Land Cruiser",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "bolt",
  },
  {
    id: 3,
    car: {
      name: "VW Crafter",
      bodyType: "VAN",
      motor: "PETROL",
      petFriendly: false,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "bolt",
  },
  {
    id: 4,
    car: {
      name: "VW ID.3",
      bodyType: "HATCHBACK",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "bolt",
  },
  {
    id: 5,
    car: {
      name: "Peugeot 208",
      bodyType: "HATCHBACK",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "citybee",
  },
  {
    id: 6,
    car: {
      name: "Ford Transit",
      bodyType: "VAN",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "MANUAL",
    },
    price: 1,
    provider: "citybee",
  },
  {
    id: 7,
    car: {
      name: "BMW X1",
      bodyType: "TOURING",
      motor: "PETROL",
      petFriendly: true,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "citybee",
  },
  {
    id: 8,
    car: {
      name: "Tesla Model 3 Standard Range",
      bodyType: "SEDAN",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "beast",
  },
  {
    id: 9,
    car: {
      name: "Tesla Model X Ludicrous Perf",
      bodyType: "TOURING",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "beast",
  },
  {
    id: 10,
    car: {
      name: "Tesla Model 3 Performance",
      bodyType: "SEDAN",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
    },
    price: 1,
    provider: "beast",
  },
  {
    id: 11,
    car: {
      name: "Rent1",
      bodyType: "HATCHBACK",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      cars: [
        "Volkswagen e-Up '19",
        "Skoda Citigo",
        "Toyota Yaris",
        "Nissan Leaf",
      ],
    },
    price: 1,
    provider: "elmo",
  },
  {
    id: 12,
    car: {
      name: "Rent5",
      bodyType: "SEDAN",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      cars: ["Tesla Model 3 SR+"],
    },
    price: 1,
    provider: "elmo",
  },
  {
    id: 13,
    car: {
      name: "Rent3",
      bodyType: "HATCHBACK",
      motor: "ELECTRIC",
      petFriendly: true,
      gearBox: "AUTOMATIC",
      cars: ["Renault Zoe", "Peugeot e-208 GT"],
    },
    price: 1,
    provider: "elmo",
  },
];
